site_name: napari-sklearn-decomposition
site_description: A simple plugin to use with napari
site_author: jdeschamps

theme: readthedocs


repo_url: https://github.com/jdeschamps/napari-sklearn-decomposition

pages:
- Home: index.md
